import { PhotoMemory, BannerStory, LoveNote } from './types';

export const PHOTO_MEMORIES: PhotoMemory[] = [
  {
    id: 'photo-1',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpjKCcCa82poE9-zOibjJdDhoooWxofCsV5uH9tnccxyLgHqQHT4APlns&s=10',
    caption: 'París, \'24 — La chispa inicial',
    date: '14 de Febrero, 2024',
    location: 'París, Francia',
    description: 'Bajo el atardecer dorado donde todo comenzó a cobrar un sentido eterno.',
    leftPage: true,
    rotationOffset: -4,
    tapePosition: 'top-left',
    annotationText: 'El día que supe que eras tú.',
  },
  {
    id: 'photo-2',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-ejIbVw_n8xCMwCDyMrZ6QzZfLBtYSb4G1RqV53DvigpxlQvjmWbFAYl6&s=10',
    caption: 'Nuestra primera cita bajo las luces',
    date: '28 de Marzo, 2024',
    location: 'Mirador del Valle',
    description: 'Aquel café helado que se transformó en cuatro horas de conversación ininterrumpida.',
    leftPage: true,
    rotationOffset: 3,
    tapePosition: 'top-right',
    annotationText: 'Tu risa iluminó toda la noche.',
  },
  {
    id: 'photo-3',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4RQufxfr-gerksw5ZjXvmG_2j3xSgiALqZWp_4JZw48sazkOOEJnmIEsP&s=10',
    caption: 'Atardecer mágico en la playa',
    date: '12 de Junio, 2024',
    location: 'Costa Dorada',
    description: 'El sonido de las olas y tus manos entrelazadas con las mías.',
    leftPage: true,
    rotationOffset: -2,
    tapePosition: 'top-center',
    annotationText: 'Promesas escritas sobre la arena.',
  },
  {
    id: 'photo-4',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqZI1g7mjvfiUqPoQ37WSsjYzOhFF7quj6NpSKajgOgw66RWE2TBCefIA&s=10',
    caption: 'Paseo de domingo y café suave',
    date: '19 de Agosto, 2024',
    location: 'Jardín Botánico',
    description: 'Las tardes sencillas que se vuelven los recuerdos más extraordinarios.',
    leftPage: false,
    rotationOffset: 4,
    tapePosition: 'top-left',
    annotationText: 'Hogar es donde tú estás.',
  },
  {
    id: 'photo-5',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2raHWpP5md-wvmPEN17EBqMvE3lkfbQaf3IHFVKksgbtrUCdMESFdvLqc&s=10',
    caption: 'Abrazos cálidos en días lluviosos',
    date: '04 de Octubre, 2024',
    location: 'Nuestra cafetería favorita',
    description: 'La lluvia afuera y nosotros resguardados en un refugio de complicidad.',
    leftPage: false,
    rotationOffset: -3,
    tapePosition: 'top-right',
    annotationText: 'El tiempo se detiene a tu lado.',
  },
  {
    id: 'photo-6',
    url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4w0XmdGGFCw5keKnoUI2J8PITQmswunl_r8Oxfm-7PS6w-8k60sPcMgE&s=10',
    caption: 'Escapada a la montaña',
    date: '22 de Noviembre, 2024',
    location: 'Sierra Nevada',
    description: 'Mirar el horizonte sintiendo que no necesitamos nada más.',
    leftPage: false,
    rotationOffset: 2,
    tapePosition: 'top-center',
    annotationText: 'Aventura tras aventura contigo.',
  },
  {
    id: 'photo-7',
    url: 'https://images.unsplash.com/photo-1518199266791-5375a83190b7?auto=format&fit=crop&q=80&w=800',
    caption: 'Bajo el cielo estrellado de medianoche',
    date: '31 de Diciembre, 2024',
    location: 'Nuestro rincón especial',
    description: 'Brindando por cada segundo vivido y por los infinitos que están por llegar.',
    leftPage: false,
    rotationOffset: -5,
    tapePosition: 'top-right',
    annotationText: 'Por un infinito juntos.',
  },
];

export const BANNER_STORIES: BannerStory[] = [
  {
    id: 'story-1',
    title: 'El Comienzo de Todo',
    subtitle: 'El viaje que transformó dos vidas independientes en un solo camino.',
    date: 'Primavera 2024',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpjKCcCa82poE9-zOibjJdDhoooWxofCsV5uH9tnccxyLgHqQHT4APlns&s=10',
    location: 'El Gran Comienzo',
    quote: 'Hay miradas que guardan conversaciones eternas antes de pronunciar una sola palabra.',
  },
  {
    id: 'story-2',
    title: 'Viajes, Mar y Risas',
    subtitle: 'Coleccionando horizontes, canciones de carretera y amaneceres únicos.',
    date: 'Verano 2024',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4RQufxfr-gerksw5ZjXvmG_2j3xSgiALqZWp_4JZw48sazkOOEJnmIEsP&s=10',
    location: 'Caminos Sin Fin',
    quote: 'A tu lado no importa el destino, porque el viaje mismo es el regalo más hermoso.',
  },
  {
    id: 'story-3',
    title: 'Hogar y Futuro',
    subtitle: 'Construyendo un amor paciente, genuino, valiente e indestructible.',
    date: 'Presente & Siempre',
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4w0XmdGGFCw5keKnoUI2J8PITQmswunl_r8Oxfm-7PS6w-8k60sPcMgE&s=10',
    location: 'Nuestro Horizonte',
    quote: 'Prometo cuidar tu corazón hoy, mañana y en cada instante que el tiempo nos conceda.',
  },
];

export const LOVE_LETTER: LoveNote = {
  title: 'Carta a Mi Amor Eterno',
  date: 'Hoy, Mañana y Siempre',
  salutation: 'Mi vida,',
  body: [
    'Si tuviera que elegir un solo instante para revivir por el resto de la eternidad, elegiría cualquiera de los días que he pasado a tu lado.',
    'A veces me detengo a mirar estas fotografías y no puedo evitar sonreír. Cada una guarda la textura de un día perfecto, el eco de tus risas y la paz inexplicable que solo siento cuando estás cerca.',
    'Gracias por ser el abrazo que calma mis tormentas, la alegría que ilumina mis mañanas y la persona con la que quiero construir cada sueño. Este álbum no es solo un registro del pasado; es el mapa de un viaje maravilloso que apenas comienza.',
    'Caminar contigo es mi mayor orgullo y mi lugar favorito en todo el universo.',
  ],
  closing: 'Con todo el amor de mi alma,',
  signature: 'Tu compañero de vida ♡',
};
